posts/urls.py
from posts import views
from django.contrib import admin
from posts import views
from django.urls import path

app_name = "posts"

urlpatterns = [
    path('', views.news, name = "news"),
    path('page/<int:page_number>', views.news, name = "page_news"),
    path('advertisements', views.advertisements, name = "advertisements"),
    path('advertisements/<int:advertisement_id>', views.one_advertisement, name = "advertisement"),
    path('create_advertisements', views.create_advertisements, name = 'create_advertisements'),
    path('create_offer', views.create_offer, name = 'create_offer'),
]

www/urls.py
from django.contrib import admin
from posts import views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.about, name = "index"),
    path("posts/", include("posts.urls")),
    path("contacts/",views.contacts, name = "contacts"),
]

posts/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=128)
    content = models.TextField(null=True, blank=True)
    date = models.DateField(auto_now=True)
    def __str__(self):
        return f"{self.title} ({self.id})"

class News(Post):
    pass

class Advertisement(Post):
    description = models.TextField(null=True, blank=True)


class Offer(Post):
    email = models.EmailField(blank= True, null= True)
    phone = PhoneNumberField(blank= True, null= True,region = 'RU')

posts/forms.py
from django import forms
from django.forms import ModelForm
from posts.models import Advertisement
from phonenumber_field.formfields import PhoneNumberField
from posts.models import Offer


class AdvertisementForm(ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={
        "class":"green",
        "placeholder": 'Название'
    }))
    content = forms.CharField(widget=forms.TextInput(attrs={
        "class":"green",
        "placeholder": 'Контент'
    }))
    description = forms.CharField(widget=forms.TextInput(attrs={
        "class":"green",
        "placeholder":'Описание'
    }))
    class Meta:
        model = Advertisement
        fields = ["title", "content", "description"]



class OfferForm(ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={
        "class":"green",
        "placeholder": ''
    }))
    content = forms.CharField(widget=forms.TextInput(attrs={
        "class":"green",
        "placeholder": 'Контент'
    }))
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        "class":"green",
        "placeholder":'xxxxx@mail.ru'
    }))
    phone = PhoneNumberField(region = 'RU', widget=forms.TextInput(attrs={
        "class":"green",
        "placeholder":'+7xxxxxxxxx'
    }))

    class Meta:
        model = Offer
        fields = ["title", "content", "email","phone"]

posts/views.py
from django.contrib.admin.templatetags.admin_list import pagination, paginator_number
from django.http import HttpResponse, HttpResponseRedirect,HttpRequest
from django.shortcuts import render
from posts.models import News, Advertisement
from django.core.paginator import Paginator
from posts.forms import AdvertisementForm, OfferForm
from django.urls import reverse
from .bot import bot

# Create your views here.

def news(request, page_number=1):
    new = News.objects.all()
    per_page = 3
    paginator = Paginator(new,per_page)
    page = paginator.page(page_number)
    context = {
    "news": page
    }
    return render(request,"posts/news.html", context)

def advertisements(request):
    advertisement = Advertisement.objects.all()
    context = {
        "advertisements": advertisement
    }
    return render(request, "posts/advertisements.html", context)

def one_advertisement(request, advertisement_id=4):
    advertisement = Advertisement.objects.get(id=advertisement_id)
    context = {
        "advertisement": advertisement
    }
    return render(request, "posts/advertisement.html", context)

def about(request):
    return render(request,'posts/about.html')

def contacts(request):
    return render(request, 'posts/contacts.html')

def create_advertisements(request):
    if request.method == "POST":
        form = AdvertisementForm(data=request.POST) #форма которую мы заполняем данными
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("posts:advertisements"))
        else:
            return HttpResponseRedirect(reverse("posts:create_advertisements"))
    elif request.method == "GET":
        form = AdvertisementForm() #пустая форма для заполнения данными
    context= {
        "form": form
    }
    return render(request, 'posts/create_advertisements.html',context)

def create_offer(request):
    if request.method == "POST":
        form = OfferForm(data=request.POST) #форма которую мы заполняем данными
        if form.is_valid():
            form.save()
            text = render(HttpRequest(),'posts/message_offer_for_tg_bot.html',{'form':form})
            bot.send_message(6216772256,text,parse_mode="HTML")
            # bot.send_message(6216772256,f'''
            # К вам поступила заявка
            # {form.cleaned_data['title']}
            # {form.cleaned_data['content']}
            # Email: {form.cleaned_data['email']}
            # 📱Номер телефона: {form.cleaned_data['phone']}
            # ''')
            return HttpResponseRedirect(reverse("posts:create_offer"))
        else:
            return HttpResponseRedirect(reverse("posts:create_offer"))
    elif request.method == "GET":
        form = OfferForm() #пустая форма для заполнения данными
    context= {
        "form": form
    }
    return render(request, 'posts/create_offer.html',context)

posts/templates/posts/about.html
{% extends "posts/base.html" %}
{% block content %}
<div>
<h1>
  О нас
</h1>
<p>
Добро пожаловать в TechNova Solutions – место, где инновации, качество и клиентоориентированность стоят на первом месте. Мы создаем передовые цифровые решения, помогая нашим клиентам достигать своих целей быстрее, удобнее и эффективнее.
</p>
<p>
Наша команда состоит из экспертов в разработке программного обеспечения, блокчейн-технологиях и искусственном интеллекте, объединенных общей миссией – делать технологии доступными для бизнеса и частных пользователей. Мы ценим прозрачность, доверие и постоянное развитие, чтобы предлагать вам лучшие решения на рынке.
</p>
<p>
Присоединяйтесь к нам, и давайте строить будущее вместе!
</p>
  </div>
{% endblock %}

posts/templates/posts/advertisement.html
{% extends "posts/base.html" %}
{% block content %}
<div class="container column" id="content">

    <div class="past">
        <h2>{{ advertisement.title }}</h2>
        <h3>Содержание</h3>
        <p>{{ advertisement.content }}</p>
        <p>{{ advertisement.date }}</p>

    </div>
</div>
{% endblock %}

posts/templates/posts/advertisements.html
{% extends "posts/base.html" %}
{% block content %}
<div class="container column" id="content">

    {%for advertisement in advertisements%}
        <div class="past">
            <h2><a href="{% url 'posts:advertisement' advertisement.id %}">{{ advertisement.title }}</a></h2>
            <p>{{ advertisement.description }}</p>
            <p>{{ advertisement.date }}</p>

        </div>
    {%endfor%}
</div>
{% endblock %}

posts/templates/posts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href='{% static "CSS/style.css" %}' rel="stylesheet">
</head>
<body>
    <!-- Navigation -->
    <nav>
        <a href="{% url 'index'%}">
            Главная
        </a>
        <a href="{% url 'posts:news'%}">
            Новости
        </a>
        <a href="{% url 'posts:advertisements'%}">
            Объявления
        </a>
        <a href="{%url 'contacts'%}">
            Контакты
        </a>
        <a href="{%url 'posts:create_advertisements'%}">
            Создать объявление
        </a>
        <a href="{%url 'posts:create_offer'%}">
            Ваши предложения
        </a>


    </nav>
    <!-- Page Content -->
    <div class="container row">
        <div class="container row" id="main">
            <!-- Дополнительная навигация -->
            <div class="container column" id="dop_nav">
                <div>1</div>
                <div>2</div>
                <div>3</div>
                <div>4</div>
            </div>
            <!-- Content -->
            {% block content %}
            {% endblock %}

        </div>
    </div>

    <footer></footer>

</body>
</html>

posts/templates/posts/contacts.html
{% extends "posts/base.html" %}
{% block content %}
<div class="container column" id="content">
    <div class="localcontacts__adress-text localcontacts__adress-text--nomar localnomargin">
        <div class="localcontacts__adress-inner">
            <b>Председатель ГСК - Очередной Евгений Прокопьевич</b>
            <a href="tel:+ 7 (916) 443 91 29">+ 7 (916) 443 91 29</a>
        </div>
        <div class="localcontacts__adress-inner">
            <b>Бухгалтер - Букреева Алевтина</b>
            <a href="tel:+ 7 (926) 603 69 68">+ 7 (926) 603 69 68</a>
        </div>
        <div class="localcontacts__adress-inner">
            <b>Электрик - Ротару Сергей</b>
            <a href="tel:+7 (985) 001 81 93">+7 (985) 001 81 93</a>
        </div>

        <div class="localcontacts__top-discription localcontacts__top-discription--nomar">
            <span>Прием звонков: с 9:00 до 18:00 (Пн-Пт)</span>
        </div>

        <div class="localcontacts__adress-inner">
            <b>Электронная почта</b>
            <div class="for-mobile-view">
                <table cellspacing="0">
                    <tbody>
                    <tr>
                        <td>
                            <div class="for-mobile-view">
                                <table cellspacing="0" style="width: 299px;">
                                    <tbody>
                                    <tr>
                                        <td style="width: 291px;">
                                            <p><strong><span style="color:#000000;"><span style="font-size:18pt;"><i
                                                    id="PH_user-email">gsk.soyz.nf@gmail.com</i></span></span></strong>
                                            </p>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="localcontacts__adress-inner">
            <b>Адрес</b>
            <span style="color:#000000;"><span style="font-size:14pt;"><span
                    style="font-family:Times New Roman,Times,serif;">143302 МО г. Наро-Фоминск, Красноармейский пер., ГСК «СОЮЗ»</span></span></span>
        </div>
        <div class="localcontacts__adress-inner">
            <b>Реквизиты компании</b>
            <p style="text-align:justify"><span style="color:#000000;"><span style="font-size:14pt;"><span
                    style="font-family:Times New Roman,Times,serif;"><span style="background:white"><span
                    style="letter-spacing:-.35pt">ГСК «СОЮЗ»&nbsp;&nbsp; Наро-Фоминское &nbsp;ОСБ №2572</span></span></span></span></span>
            </p>

            <p><span style="color:#000000;"><span style="font-size:14pt;"><span
                    style="font-family:Times New Roman,Times,serif;"><span style="background:white"><span
                    style="letter-spacing:-.05pt">Р/счет № 40703810840270000229</span></span></span></span></span></p>

            <p><span style="color:#000000;"><span style="font-size:14pt;"><span
                    style="font-family:Times New Roman,Times,serif;"><span style="background:white"><span
                    style="letter-spacing:-.1pt">БИК 044525225</span></span></span></span></span></p>

            <p><span style="color:#000000;"><span style="font-size:14pt;"><span
                    style="font-family:Times New Roman,Times,serif;"><span style="background:white">К/с 30101810400000000225</span></span></span></span>
            </p>

            <p><span style="color:#000000;"><span style="font-size:14pt;"><span
                    style="font-family:Times New Roman,Times,serif;"><span style="background:white">ИНН 5030029528; КПП 503001001;&nbsp;</span></span></span></span>
            </p>

            <p style="margin-right:41px"><span style="color:#000000;"><span style="font-size:14pt;"><span
                    style="font-family:Times New Roman,Times,serif;"><span style="background:white"><span
                    style="letter-spacing:-.05pt">Банк получателя: Сбербанк России&nbsp;</span></span></span></span></span>
            </p>
        </div>
    </div>
</div>
{% endblock %}

posts/templates/posts/create_advertisements.html
{% extends "posts/base.html" %}
{% block content %}
<div class="container column" id="content">
    <form action="{% url 'posts:create_advertisements'%}" method="post">
        {% csrf_token %}
        <div>
            <label for="{{form.title.id_for_lable}}">

            </label>
            {{form.title}}
        </div>
        <div>
            <label for="{{form.content.id_for_lable}}">

            </label>
            {{form.content}}
        </div>
        <div>
            <label for="{{form.description.id_for_lable}}">

            </label>
            {{form.description}}
        </div>
        <button type="submit">Submit</button>
    </form>

</div>
{% endblock %}

posts/templates/posts/create_offer.html
{% extends "posts/base.html" %}
{% block content %}
<div class="container column" id="content">
    <form action="{% url 'posts:create_offer'%}" method="post">
        {% csrf_token %}
        <div>
            <label for="{{form.title.id_for_lable}}">

            </label>
            {{form.title}}
        </div>
        <div>
            <label for="{{form.content.id_for_lable}}">

            </label>
            {{form.content}}
        </div>
        <div>
            <label for="{{form.email.id_for_lable}}">

            </label>
            {{form.email}}
        </div>

        <div>
            <label for="{{form.phone.id_for_lable}}">

            </label>
            {{form.phone}}
        </div>
        <button type="submit">Submit</button>
    </form>

</div>
{% endblock %}

posts/templates/posts/message_offer_for_tg_bot.html
К вам поступила заявка
{{form.title.value}}
{{form.content.value}}
Email: {{form.email.value}}
📱<b>Номер телефона:</b> {{form.phone.value}}

posts/templates/posts/news.html
{% extends "posts/base.html" %}
{% block content %}

<div class="container column" id="content">

    {%for new in news%}
        <div class="past">
            <h2>{{ new.title }}</h2>
            <p>{{ new.content }}</p>
            <p>{{ new.date }}</p>
        </div>
    {%endfor%}
    <div>
        <a class="disable"></a>
        <a class="{%if not news.has_previous%} disable {%endif%}" href="
            {% if news.has_previous%}
                {% url 'posts:page_news' news.previous_page_number  %}
            {%else %}
                #
            {%endif%}">
            <=
        </a>

        {% for page in news.paginator.page_range %}
        <a href="{% url 'posts:page_news' page %}">{{page}}</a>
        {%endfor%}
        <a class="{%if not news.has_next%} disable {%endif%}" href="
            {% if news.has_next%}
                {% url 'posts:page_news' news.next_page_number  %}
            {%else %}
                #
            {%endif%}">
            =>
        </a>
    </div>
</div>

{% endblock %}